import "../components/styles/globals.css";
import Navbar from "../components/shared/Navbar";
import Header from "../components/shared/Header";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Middle Ground Treatment and Training</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Header />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
