import "../components/styles/globals.css";
import Navbar from "../components/shared/Nav/Navbar";
import Header from "../components/shared/Header";
import Footer from "../components/shared/Footer";
import BodyWrapper from "../components/shared/BodyWrapper";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Middle Ground Treatment and Training</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link
          rel="stylesheet"
          href="https://use.typekit.net/zcn8wvz.css"
        ></link> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <BodyWrapper>
        <Component {...pageProps} />
      </BodyWrapper>
      <Footer />
    </>
  );
}

export default MyApp;
